export default [
    {
        id: 1,
        picture: 'https://i.ibb.co/Yf30Y6K/animal-Shelter-min.png',
        name: 'Child Support',
        email: 'bernadettewitt@zensor.com',
        phone: '+1 (976) 583-3090',
        date: '',
    },
    {
        id: 2,
        picture: 'https://i.ibb.co/HqtN5Hq/baby-Sit-min.png',
        name: 'Refuge shelter',
        email: 'meltonheath@zensor.com',
        phone: '+1 (981) 474-3284',
        date: '',
    },
    {
        id: 3,
        picture: 'https://i.ibb.co/1fJmC2M/bird-House-min.png',
        name: 'Food Charity',
        email: 'chenwilson@zensor.com',
        phone: '+1 (863) 424-3937',
        date: '',
    },
    {
        id: 4,
        picture: 'https://i.ibb.co/cw4gfrH/child-Support-min.png',
        name: 'Host a clothing swap.',
        email: 'shepardfreeman@zensor.com',
        phone: '+1 (806) 561-3405',
        date: '',
    },
    {
        id: 5,
        picture: 'https://i.ibb.co/qk0wptY/clean-Water-min.png',
        name: 'Host a river clean-up.',
        email: 'deckerschwartz@zensor.com',
        phone: '+1 (873) 479-3974',
        date: '',
    },
    {
        id: 6,
        picture: 'https://i.ibb.co/Sfhtk00/clearn-Park-min.png',
        name: 'Clean water for children',
        email: 'mossmaynard@zensor.com',
        phone: '+1 (964) 491-2918',
        date: '',
    },
    {
        id: 7,
        picture: 'https://i.ibb.co/HBYqsRV/cloth-Swap-min.png',
        name: 'Good education',
        email: 'pickettedwards@zensor.com',
        phone: '+1 (995) 542-2641',
        date: '',
    },
    {
        id: 8,
        picture: 'https://i.ibb.co/d7RmJ51/drive-Safety-min.png',
        name: 'New books for children',
        email: 'kristenkoch@zensor.com',
        phone: '+1 (954) 488-3509',
        date: '',
    },
    {
        id: 9,
        picture: 'https://i.ibb.co/yQQPyL3/extra-Volunteer-min.png',
        name: 'Host a study group.',
        email: 'elizakeith@zensor.com',
        phone: '+1 (946) 436-3206',
        date: '',
    },
    {
        id: 10,
        picture: 'https://i.ibb.co/h81M64L/food-Charity-min.png',
        name: 'Build birdhouses for your neighbors.',
        email: 'noellealvarez@zensor.com',
        phone: '+1 (877) 413-2960',
        date: '',
    },
    {
        id: 11,
        picture: 'https://i.ibb.co/V2rnPvb/vote-Register-min.png',
        name: 'Organize books at the library.',
        email: 'doraroberson@zensor.com',
        phone: '+1 (835) 461-2463',
        date: '',
    },
    {
        id: 12,
        picture: 'https://i.ibb.co/Nn6h5qS/ITHelp-min.png',
        name: 'Give a seminar on  driving safety.',
        email: 'mcknightelliott@zensor.com',
        phone: '+1 (865) 442-3921',
        date: '',
    },
    {
        id: 13,
        picture: 'https://i.ibb.co/NnjVRK1/library-Books-min.png',
        name: 'Give free music lessons.',
        email: 'elviracarson@zensor.com',
        phone: '+1 (902) 430-3293',
        date: '',
    },
    {
        id: 14,
        picture: 'https://i.ibb.co/54Rs6dJ/music-Lessons-min.png',
        name: 'Teach people how to register to vote.',
        email: 'corrinepatton@zensor.com',
        phone: '+1 (845) 450-2335',
        date: '',
    },
    {
        id: 15,
        picture: 'https://i.ibb.co/fk1jwfx/new-Books-min.png',
        name: 'Clean up your local park.',
        email: 'sweeneyjames@zensor.com',
        phone: '+1 (842) 553-2715',
        date: '',
    },
    {
        id: 16,
        picture: 'https://i.ibb.co/FHv70dV/refuse-Shelter-min.png',
        name: 'Give IT help to local adults',
        email: 'jeanniesmith@zensor.com',
        phone: '+1 (807) 501-2082',
        date: '',
    },
    {
        id: 17,
        picture: 'https://i.ibb.co/3TFZp5M/river-Clean-min.png',
        name: 'Foster a shelter animal.',
        email: 'frederickblack@zensor.com',
        phone: '+1 (984) 427-3400',
        date: '',
    },
    {
        id: 18,
        picture: 'https://i.ibb.co/8zmytyb/school-Suffiles-min.png',
        name: 'CBabysit during PTA meetings.',
        email: 'cassandraholman@zensor.com',
        phone: '+1 (860) 431-2177',
        date: '',
    },
    {
        id: 19,
        picture: 'https://i.ibb.co/6WTP9CS/study-Group-min.png',
        name: 'Collect stuffed  animals.',
        email: 'hannahsampson@zensor.com',
        phone: '+1 (978) 578-2606',
        date: '',
    },
    {
        id: 20,
        picture: 'https://i.ibb.co/8dKy8g3/stuffed-Animals-min.png',
        name: 'Collect school supplies.',
        email: 'bowerscooke@zensor.com',
        phone: '+1 (824) 436-2953',
        date: '',
    },
];
